export const css = {
  unsolvedButton: 'unsolved-float-button',
  unsolvedLogo: 'unsolved-logo',
  unsolvedLogoBig: 'unsolved-logo-big',
  unsolvedPanel: 'unsolved-panel',
  clicked: 'clicked',
  login: 'login',
  loginButton: 'login-button',
  loginButtonLogo: 'login-button-logo',
  loginButtonMessage: 'login-button-message',
  contentContainer: 'content-container',
  contentTitle: 'content-title',
  contentBody: 'content-body',
  contentNavigator: 'content-navigator',
  contentNavigatorHr: 'content-navigator-hr',
  contentNavigatorSetting: 'content-navigator-setting',
  contentNavigatorLogos: 'content-navigator-logos',
  contentNavigatorTexts: 'content-navigator-texts',
};
